In [2]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [3]:
import pandas as pd  # noqa: F401
import numpy as np
import json
from pprint import pprint
import sys
import os
from pyam import IamDataFrame, Statistics, filter_by_meta  # noqa: F401

sys.path.append('..')
from src.iasa.iiasa_client import IIASABaseAPIClient
from src.iasa.utils import create_df_from_api_response

[WARNING] 12:21:38 - pint.util: Redefining 'kt' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 12:21:38 - pint.util: Redefining 'EUR_2005' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)
[WARNING] 12:21:38 - pint.util: Redefining 'EUR' (<class 'pint.delegates.txt_defparser.plain.UnitDefinition'>)

In [4]:
client = IIASABaseAPIClient()

### 1. Runs Endpoint

In [15]:
runs_df = create_df_from_api_response(client.get_data(
    "runs/",
    params={
        "join_parameters": "true",
        "join_runs": "true",
        "table": "true",
    }, ))
runs_df

,model__id,scenario__id,version,is_default,id,updated_at,updated_by,created_at,created_by
0,1,1,1,True,1,2025-03-28 12:04:39.091252,@unknown,2025-03-28 12:04:24.885658,@unknown
1,1,2,1,True,2,2025-03-28 12:04:45.359392,@unknown,2025-03-28 12:04:39.918461,@unknown
2,1,3,1,True,3,2025-03-28 12:04:52.187804,@unknown,2025-03-28 12:04:46.039148,@unknown
3,1,4,1,True,4,2025-03-28 12:04:58.703293,@unknown,2025-03-28 12:04:52.911709,@unknown
4,1,5,1,True,5,2025-03-28 12:05:05.292936,@unknown,2025-03-28 12:04:59.544864,@unknown
...,...,...,...,...,...,...,...,...,...
1136,41,407,1,True,1158,2025-08-05 19:56:06.253031,@unknown,2025-08-05 19:55:58.805093,@unknown
1137,41,408,1,True,1159,2025-08-05 19:56:14.414347,@unknown,2025-08-05 19:56:06.321821,@unknown
1138,41,409,1,True,1160,2025-08-05 19:56:22.345297,@unknown,2025-08-05 19:56:14.483553,@unknown
1139,41,410,1,True,1161,2025-08-05 19:56:30.569370,@unknown,2025-08-05 19:56:22.414333,@unknown
1140,41,411,1,True,1162,2025-08-05 19:56:38.573245,@unknown,2025-08-05 19:56:30.638476,@unknown

### 2. Regions Endpoint

In [6]:
runs_df = create_df_from_api_response(client.get_data(
    "regions/",
    params={"table": "true"}
))
runs_df

,name,hierarchy,id,created_at,created_by
0,World,common,318,2025-03-20 15:11:06.387377,@unknown
1,International,common,320,2025-03-28 11:50:38.561727,@unknown
2,OECD & EU (R5),R5,321,2025-03-28 11:50:38.810880,@unknown
3,Reforming Economies (R5),R5,322,2025-03-28 11:50:38.858697,@unknown
4,Asia (R5),R5,323,2025-03-28 11:50:38.909370,@unknown
...,...,...,...,...,...
597,REMIND-MAgPIE 3.5-4.11|Russia and Reforming Ec...,REMIND-MAgPIE 3.5-4.11,916,2025-07-14 16:40:33.673106,@unknown
598,REMIND-MAgPIE 3.5-4.11|Sub-Saharan Africa,REMIND-MAgPIE 3.5-4.11,917,2025-07-14 16:40:33.703406,@unknown
599,REMIND-MAgPIE 3.5-4.11|United States of America,REMIND-MAgPIE 3.5-4.11,918,2025-07-14 16:40:33.731659,@unknown
600,REMIND-MAgPIE 3.5-4.11|EU 28,REMIND-MAgPIE 3.5-4.11,919,2025-07-14 16:40:33.771070,@unknown
601,REMIND-MAgPIE 3.5-4.11|Non-EU28 Europe,REMIND-MAgPIE 3.5-4.11,920,2025-07-14 16:40:33.802049,@unknown

### 3. Variables Endpoint

In [7]:
variables = create_df_from_api_response(client.get_data(
    "iamc/variables/",
    params={"table": "true"}
))
variables

,name,id,created_at,created_by
0,Agricultural Demand,1,2025-03-28T12:04:25.352595,@unknown
1,Agricultural Production|Crops|Energy Crops,2,2025-03-28T12:04:25.396617,@unknown
2,Capacity Additions|Electricity|Biomass,3,2025-03-28T12:04:25.436362,@unknown
3,Capacity Additions|Electricity|Coal,4,2025-03-28T12:04:25.475249,@unknown
4,Capacity Additions|Electricity|Gas,5,2025-03-28T12:04:25.513302,@unknown
...,...,...,...,...
1979,Final Energy|Industry|Chemicals|Ammonia|Electr...,2020,2025-08-04T16:02:44.162829,@unknown
1980,Final Energy|Industry|Chemicals|Ammonia|Gases|...,2021,2025-08-04T16:02:44.210354,@unknown
1981,Final Energy|Industry|Chemicals|Ammonia|Liquid...,2022,2025-08-04T16:02:44.257245,@unknown
1982,Final Energy|Industry|Chemicals|Ammonia|Other,2023,2025-08-04T16:02:44.294017,@unknown
1983,Final Energy|Transportation|Passenger|Gases|Fo...,2024,2025-08-04T16:02:44.463070,@unknown

### 4. Models Endpoint

In [8]:
models = create_df_from_api_response(
    client.get_data(
        "models/",
        params={
            "join_parameters": "true",
            "join_runs": "true",
            "table": "true",
        },
    )
)

models

                                name  id                 created_at created_by
0                       AIM/CGE V2.2   1 2025-03-28 12:04:24.863850   @unknown
1              MESSAGEix-GLOBIOM 1.1   2 2025-03-28 12:40:19.727393   @unknown
2                          IMAGE 3.0   3 2025-03-28 12:59:05.024707   @unknown
3                          WITCH 5.0   4 2025-03-28 13:22:19.746918   @unknown
4                         COFFEE 1.1   5 2025-03-28 13:34:43.084588   @unknown
5                       GEM-E3 V2021   6 2025-03-28 14:11:53.838058   @unknown
6                   POLES-JRC ENGAGE   7 2025-03-28 16:44:53.587610   @unknown
7              REMIND-MAgPIE 2.1-4.2   8 2025-04-02 08:18:31.620923   @unknown
8                       TIAM-ECN 1.1   9 2025-04-02 10:21:00.357146   @unknown
9                         REMIND 3.0  10 2025-04-07 07:41:37.045853   @unknown
10                     PROMETHEUS V1  11 2025-04-07 07:57:18.419906   @unknown
11                        COFFEE 1.5  12 2025-04-07 08:00:56.636372   @unknown
12     MESSAGEix-GLOBIOM 1.1-BMT-R12  13 2025-04-07 08:57:25.651643   @unknown
13                       IMACLIM 2.0  14 2025-04-07 10:56:51.371817   @unknown
14      MESSAGEix-GLOBIOM 1.1-BM-R12  15 2025-04-07 11:12:01.131619   @unknown
15                     ODYM-RECC 2.5  16 2025-04-07 11:17:15.351178   @unknown
16             REMIND-MAgPIE 3.2-4.6  17 2025-04-07 11:32:02.462291   @unknown
17                     GCAM 6.0 NGFS  18 2025-04-07 11:59:14.504722   @unknown
18  MESSAGEix-GLOBIOM 2.0-M-R12-NGFS  19 2025-04-07 12:05:32.557960   @unknown
19             REMIND-MAgPIE 3.3-4.8  20 2025-04-07 12:12:40.234504   @unknown
20                         IMAGE 3.3  21 2025-04-09 07:54:45.137085   @unknown
21                      GEM-E3 v2023  22 2025-07-07 11:23:19.040164   @unknown
22                         IMAGE 3.2  23 2025-07-07 11:23:56.886279   @unknown
23                       AIM/CGE 2.0  24 2025-07-25 20:28:26.246687   @unknown
24                          GCAM 4.2  25 2025-07-25 20:28:37.217708   @unknown
25                       IMAGE 3.0.1  26 2025-07-25 20:28:41.043806   @unknown
26               MESSAGE-GLOBIOM 1.0  27 2025-07-25 20:29:11.067316   @unknown
27                 REMIND-MAgPIE 1.5  28 2025-07-25 20:29:29.722320   @unknown
28                 WITCH-GLOBIOM 3.1  29 2025-07-25 20:29:52.825180   @unknown
29                          GCAM 5.3  30 2025-07-28 15:51:49.731020   @unknown
30                       AIM/CGE 2.1  31 2025-07-28 19:12:56.037618   @unknown
31                    POLES GECO2019  32 2025-07-28 19:17:38.447019   @unknown
32             REMIND-MAgPIE 1.7-3.0  33 2025-07-28 19:20:40.032207   @unknown
33             MESSAGEix-GLOBIOM 1.0  34 2025-07-29 12:43:46.697096   @unknown
34                    POLES CD-LINKS  35 2025-07-29 12:44:09.813478   @unknown
35                 WITCH-GLOBIOM 4.4  36 2025-07-29 12:47:47.461760   @unknown
36                     C-ROADS-5.005  37 2025-07-30 10:57:27.769050   @unknown
37                AIM/Hub-Global 2.0  38 2025-07-30 11:14:37.531014   @unknown
38                        REMIND 1.7  39 2025-07-30 11:56:53.782979   @unknown
39                        REMIND 2.1  40 2025-07-30 12:19:07.456092   @unknown
40             MESSAGEix-GLOBIOM_1.2  41 2025-08-05 19:54:04.047023   @unknown

### 5. Scenarios Endpoint

In [9]:
scenarios = create_df_from_api_response(client.get_data(
    "scenarios/",
    params={"table": "true"}
))
scenarios

,name,id,created_at,created_by
0,ENGAGE-INDCi2030-1000f,1,2025-03-28 12:04:24.883425,@unknown
1,ENGAGE-INDCi2030-1200,2,2025-03-28 12:04:39.918461,@unknown
2,ENGAGE-INDCi2030-1200f,3,2025-03-28 12:04:46.039148,@unknown
3,ENGAGE-INDCi2030-1400,4,2025-03-28 12:04:52.911709,@unknown
4,ENGAGE-INDCi2030-1400f,5,2025-03-28 12:04:59.544864,@unknown
...,...,...,...,...
406,COVID-Shift-SelfReliance_max_GDP,407,2025-08-05 19:55:58.805093,@unknown
407,COVID-Shift-SelfReliance_min_GDP,408,2025-08-05 19:56:06.321821,@unknown
408,COVID-Shift-SmartUse,409,2025-08-05 19:56:14.483553,@unknown
409,COVID-Shift-SmartUse_1000,410,2025-08-05 19:56:22.414333,@unknown
410,COVID-Shift-SmartUse_550,411,2025-08-05 19:56:30.638476,@unknown

### 6. Meta Endpoint

In [5]:
meta = create_df_from_api_response(client.get_data(
    "meta/",
    params={"table": "True", "join_parameters": "true", "join_runs": "true", "limit": 100000}
))
meta

,run__id,key,id,value,type
0,1,Project,1,H2020 ENGAGE,STR
1,1,Scientific Manuscript (Citation),2,Riahi et al. (2021),STR
2,1,Scientific Manuscript (DOI),3,10.1038/s41558-021-01215-2,STR
3,1,Data Source (DOI),4,10.5281/zenodo.5553976,STR
4,2,Project,5,H2020 ENGAGE,STR
...,...,...,...,...,...
70054,1204,Climate Assessment|Category [Name],116035,C8: Above 4.0°C,STR
70055,1204,Climate Assessment|Processing|Harmonization,116036,aneris (version: 0.3.1),STR
70056,1204,Climate Assessment|Processing|Infilling,116037,silicone (version: 1.3.0),STR
70057,1204,Climate Assessment|Processing|Runner,116038,openscm_runner (version: 0.12.1),STR
70058,1204,Climate Assessment|Processing|Package,116039,climate-assessment (version: 0.1.4a0),STR

In [11]:
# explore meta indicators
metaindicators = create_df_from_api_response(
    client.get_data(
        "meta/",
        params={"join_run_index": "true", "table": "true"},
        body={"run": {"default_only": False}},
    )
)

metaindicators

,model,scenario,version,key,id,value,type
0,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,Project,1,H2020 ENGAGE,STR
1,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,Scientific Manuscript (Citation),2,Riahi et al. (2021),STR
2,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,Scientific Manuscript (DOI),3,10.1038/s41558-021-01215-2,STR
3,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,Data Source (DOI),4,10.5281/zenodo.5553976,STR
4,AIM/CGE V2.2,ENGAGE-INDCi2030-1200,1,Project,5,H2020 ENGAGE,STR
...,...,...,...,...,...,...,...
49995,WITCH 5.0,COMMIT-2°C-2030,1,Climate Assessment|Year of Peak Warming|67th P...,84278,2069.0,INT
49996,WITCH 5.0,COMMIT-2°C-2030,1,Climate Assessment|Year of Peak Warming|75th P...,84279,2070.0,INT
49997,WITCH 5.0,COMMIT-2°C-2030,1,Climate Assessment|Year of Peak Warming|83th P...,84280,2082.0,INT
49998,WITCH 5.0,COMMIT-2°C-2030,1,Climate Assessment|Year of Peak Warming|90th P...,84281,2093.0,INT
49999,WITCH 5.0,COMMIT-2°C-2030,1,Climate Assessment|Year of Peak Warming|95th P...,84282,2093.0,INT

In [12]:
# explore meta indicators
metaindicators = create_df_from_api_response(
    client.get_data(
        "meta/",
        params={"join_run_index": "false", "table": "true"},
        body={"run": {"id__in": [1, 2]}},
    )
)

metaindicators

,run__id,key,id,value,type
0,1,Project,1,H2020 ENGAGE,STR
1,1,Scientific Manuscript (Citation),2,Riahi et al. (2021),STR
2,1,Scientific Manuscript (DOI),3,10.1038/s41558-021-01215-2,STR
3,1,Data Source (DOI),4,10.5281/zenodo.5553976,STR
4,2,Project,5,H2020 ENGAGE,STR
...,...,...,...,...,...
127,1,Reason For Concern|Exceeding Prudent Limit For...,96747,ok,STR
128,2,Emissions Diagnostics|Cumulative CCS [2020-210...,96748,893.849624,FLOAT
129,2,Reason For Concern|Exceeding Prudent Limit For...,96749,ok,STR
130,1,Reason For Concern|Sustainable Bioenergy Use|W...,98664,high,STR
131,2,Reason For Concern|Sustainable Bioenergy Use|W...,98665,high,STR

In [13]:
data = create_df_from_api_response(
    client.get_data(
        "iamc/datapoints/",
        params={"join_run_index": "false", "join_parameters": "true", "join_runs": "true", "table": "true"},
        body={
            "variable": {"name__in": ["Agricultural Demand"]},
            "region": {"name__in": ["World"]},
        },
    )
)

data

,model,scenario,version,region,unit,variable,value,type,step_year,time_series__id,id
14,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,World,million t DM/yr,Agricultural Demand,2729.930700,ANNUAL,2010,3026,57490
11,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,World,million t DM/yr,Agricultural Demand,3179.632000,ANNUAL,2015,3026,57487
9,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,World,million t DM/yr,Agricultural Demand,3515.388600,ANNUAL,2020,3026,57485
13,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,World,million t DM/yr,Agricultural Demand,3804.129000,ANNUAL,2025,3026,57489
18,AIM/CGE V2.2,ENGAGE-INDCi2030-1000f,1,World,million t DM/yr,Agricultural Demand,4010.673800,ANNUAL,2030,3026,57494
...,...,...,...,...,...,...,...,...,...,...,...
10300,MESSAGEix-GLOBIOM 1.0,LowEnergyDemand_1.3_IPCC,1,World,million t DM/yr,Agricultural Demand,5960.851082,ANNUAL,2060,6653477,170402937
10301,MESSAGEix-GLOBIOM 1.0,LowEnergyDemand_1.3_IPCC,1,World,million t DM/yr,Agricultural Demand,6545.736524,ANNUAL,2070,6653477,170402938
10302,MESSAGEix-GLOBIOM 1.0,LowEnergyDemand_1.3_IPCC,1,World,million t DM/yr,Agricultural Demand,7007.148930,ANNUAL,2080,6653477,170402939
10303,MESSAGEix-GLOBIOM 1.0,LowEnergyDemand_1.3_IPCC,1,World,million t DM/yr,Agricultural Demand,7206.339032,ANNUAL,2090,6653477,170402940
10304,MESSAGEix-GLOBIOM 1.0,LowEnergyDemand_1.3_IPCC,1,World,million t DM/yr,Agricultural Demand,7132.685876,ANNUAL,2100,6653477,170402941